[package]
name = "locus-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
futures.workspace = true
locus-core = { path = "../core" }
thiserror.workspace = true
tokio.workspace = true
